USE db_centrales;

REPLACE INTO USUARIO(TIPO_DOCUMENTO, NUMERO_DOCUMENTO, REPORTADO_CENTRALES) VALUES('CC', 12345678912, 'S');
REPLACE INTO USUARIO(TIPO_DOCUMENTO, NUMERO_DOCUMENTO, REPORTADO_CENTRALES) VALUES('CC', 123456789, 'N');